### ISSUE TITLE
关于项目文档编写的一些思考和实践

### ISSUE THREAD

**Issue by franksun2013** [PLM-Person-Life-Management-Sytem/gitblog#9]
# 关于项目文档编写的一些思考和实践

![tech_doc](https://user-images.githubusercontent.com/42464504/123533668-c1dcf580-d749-11eb-84f4-6637d63162ed.jpg)

> 2021-01-30 19:43:21

关于项目文档编写的一些思考和实践，分享我的选择文档工具的标准，日常写文档 flow 和工具推荐

本文知识简单的讨论，不涉及到项目文档的一些很具体的写作手法，可以推荐一份 Google 的学习资源 [Google 技术写作课程](https://developers.google.com/tech-writing)，里面也提到了一个很重要的概念「Every engineer is also a writer.」，最佳实践可以参考[Google 开发者文档风格](https://developers.google.com/style)，当然也可以参考一下现在非常优秀的开源作品，比如 Vue、requests 等；

## 为什么需要一份好的文档

一个成功的项目除了一些必须的因素之外，一个好的测试覆盖率、文档、维护活跃度、推广等等都是不可或缺的，软件工程不是代码工程，文档是软件工程中一个很重要的事情！一个项目映入眼帘的第一个是 README 文档，简单的介绍项目的内容和特色等，再往下就是项目文档，把整个项目 10% 的时间用来写文档也不为过！

如果一个项目连文档都很应付，你能期待项目的代码写的会很好吗？

## 什么才是一个好的文档工具

我认为一个好的文档工具应该有一下的特点：

1. 和项目可以在一起，并不会污染代码，源文件可以纳入版本控制系统
2. 自动化生成，基于源文件，一般都是 markdown 格式，要有一个命令行或者脚手架解决
3. 可配置、可拓展、可自定义
4. 文档的页面直观、简单，该有的基础文档功能都内置
5. 自动化部署

6. **文档工具也应该有好的文档说明，如果没有，那这个工具是不可信赖的**

### 工具选择

现在市面上好用的文档工具很多，按照各自喜好选择就可以了，工具最好能遵循上文的 6 个原则；

我选择的是基于 Python 的 [mkdocs-material](https://squidfunk.github.io/mkdocs-material/)，使用了 materical 风格设计；

### 工作流

1. 根目录配置文件，我有一个模板，一般配置好直接使用就好了，类似下面的格式，可以观看官方文档；

```yaml
# Project information

site_name: My blog backup
site_url: https://sunyunxian.github.io/blog-doc-backup/
site_author: Martin Donath
site_description: >-
  personal blog backup, 个人博客文章备份
# Repository
repo_name: sunyunxian/blog-doc-backup
repo_url: https://github.com/sunyunxian/blog-doc-backup
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 - 2021 FrankSun

# Configuration
theme:
  name: material
  palette:
    scheme: preference
    primary: indigo

# Page tree
nav:
  - 2020:
    - 关于大学: blog/2020/关于大学.md
  - 2021:
    - 手机软件使用: blog/2021/手机软件使用.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sunyunxian
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/youtai2020

# 自定义的 css 和 js
extra_css:
  - blog/stylesheets/extra.css

extra_javascript:
  - blog/javascripts/extra.js

# Plugins
plugins:
  - search

# Customization

# Google Analytics
```

2. 根目录下增加 doc 文件夹，在此文件夹下编写/修改 md 文件，在配置文件中的 `nav:` 下修改文档的顺序就好了；

3. 使用 Github Action，写一个 yaml 自动部署文档，会自动生成文档，这个文档会在一个 `gh-pages` 分支下，使用 setting 下 Github page 即可，可以说 push 完后，文档就完成了自动化更新和部署，下面是 ci 的文件实例；

```yaml
name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
```

基本上就是三个步骤，可以说只要写好 markdown 文档，剩下的事情就可以交给自动化了，非常方便；

以上只是我的个人使用实践，欢迎分享你的实践！

## 工具推荐

一些开源的文档写作工具，直接去看官方文档就好了，非常直观清晰

[docsify](https://docsify.js.org/#/) 基于 nodejs 的文档生成工具

[mkdocs](https://www.mkdocs.org/) 基于 Python 开发的一个文档生成工具

[mkdocs-material](https://squidfunk.github.io/mkdocs-material/) mkdocs 的一个主题，使用 materical 风格设计；
